# Generated by Django 5.2.8 on 2025-11-22 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва навички')),
                ('slug', models.SlugField(unique=True, verbose_name='URL ідентифікатор')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('difficulty', models.IntegerField(choices=[(1, 'Novice'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1, verbose_name='Складність')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
            },
        ),
        migrations.CreateModel(
            name='SkillDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('hard', 'Обовʼязково'), ('soft', 'Бажано')], default='hard', max_length=10)),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='skills.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Залежність',
                'verbose_name_plural': 'Залежності',
                'unique_together': {('from_skill', 'to_skill')},
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='dependencies',
            field=models.ManyToManyField(related_name='related_to', through='skills.SkillDependency', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'Треба вивчити'), ('in_progress', 'В процесі'), ('done', 'Завершено')], default='todo', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогрес користувача',
                'verbose_name_plural': 'Прогрес користувачів',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
