# Generated by Django 5.2.8 on 2025-11-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на відео (YouTube)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис (Markdown)'),
        ),
    ]
