# Generated by Django 5.2.8 on 2025-11-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_video_url_alter_skill_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'difficulty', 'title'], 'verbose_name': 'Навичка', 'verbose_name_plural': 'Навички'},
        ),
    ]
