# Generated by Django 5.2.8 on 2025-11-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL ідентифікатор'),
        ),
    ]
