# Generated by Django 5.2.8 on 2025-11-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Темна тема'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Показувати в рейтингу'),
        ),
    ]
