# Generated by Django 5.2.8 on 2025-11-25 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_profile_dark_mode_profile_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', '🐛 Помилка / Баг'), ('feature', '💡 Ідея / Пропозиція'), ('other', '📝 Інше')], default='other', max_length=20, verbose_name='Категорія')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Вирішено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Зворотний зв'язок",
                'verbose_name_plural': "Зворотний зв'язок",
                'ordering': ['-created_at'],
            },
        ),
    ]
